// <auto-generated />
namespace AstAppDL.DataContexts.ApplicationDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PoolIsActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PoolIsActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201704092149120_PoolIsActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
